dist: trusty

language:
  - python
python:
  - "2.7"

cache:
  directories:
    - download
    - data

before_install:
  - deactivate  # leaving Travis' virtualenv first since otherwise Jupyter/IPython gets confused with conda inside a virtualenv (See: https://github.com/ipython/ipython/issues/8898)
  - mkdir -p download
  - cd download
  - travis_retry wget -c http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -f -p ~/miniconda
  - cd ..
  - export PATH=~/miniconda/bin:$PATH
  - conda update --yes conda

install:
  # Install binary distribution of scientific python modules
  - test -e ~/miniconda/envs/test/bin/activate || ( rm -rf ~/miniconda/envs/test; conda create --yes -n test python=$TRAVIS_PYTHON_VERSION )
  - source activate test
  - conda install --yes numpy scipy pip
  # Install all remaining dependencies as per our README
  - pip install -r python-package-requirements.txt

script:

  # Download data
  - chmod +x scripts/get_polarity.sh
  - scripts/get_polarity.sh
  - chmod +x scripts/get_senna.sh
  - scripts/get_senna.sh
  - chmod +x scripts/get_word_freq.sh
  - scripts/get_word_freq.sh
  # Run test
  #- python shalo_test.py
  - python fit_model.py fasttext config/polarity.json
